import type { Metadata } from "next";
import { LiffProvider } from "@/components/LiffProvider"
import "./globals.css";

export const metadata: Metadata = {
  title: "eQOL予約",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ja">
      <body className="w-screen h-screen">
        <LiffProvider liffId={process.env.NEXT_PUBLIC_LIFF_ID || ''}>
          {children}
        </LiffProvider>
      </body>
    </html>
  );
}
